# Generated by Django 6.0.7 on 2026-07-26 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('create', 'Создание записи'), ('update', 'Изменение записи'), ('delete', 'Удаление записи'), ('export', 'Выгрузка отчёта'), ('import', 'Загрузка данных'), ('admin', 'Административное действие')], db_index=True, max_length=16, verbose_name='Действие')),
                ('entity', models.CharField(blank=True, default='', max_length=64, verbose_name='Объект')),
                ('entity_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Идентификатор')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='Описание')),
                ('path', models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес запроса')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('request_id', models.CharField(blank=True, default='', max_length=32, verbose_name='Идентификатор запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие журнала',
                'verbose_name_plural': 'Журнал действий',
                'db_table': 'app_audit_event',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ComparisonSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('kind', models.CharField(choices=[('district', 'Округа'), ('object', 'Объекты инфраструктуры'), ('route', 'Грузовые маршруты')], default='district', max_length=16, verbose_name='Тип сравнения')),
                ('members', models.CharField(default='', max_length=500, verbose_name='Состав набора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Набор сравнения',
                'verbose_name_plural': 'Наборы сравнения',
                'db_table': 'app_comparison_set',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование отчёта')),
                ('dataset', models.CharField(max_length=64, verbose_name='Набор данных')),
                ('fmt', models.CharField(choices=[('xlsx', 'Электронная таблица XLSX'), ('docx', 'Документ Word DOCX'), ('csv', 'Таблица CSV'), ('pdf', 'Документ PDF'), ('geojson', 'Слой GeoJSON')], max_length=16, verbose_name='Формат')),
                ('query', models.CharField(blank=True, default='', max_length=1000, verbose_name='Условия отбора')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('done', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='Состояние')),
                ('file_name', models.CharField(blank=True, default='', max_length=250, verbose_name='Имя файла')),
                ('file_size', models.IntegerField(default=0, verbose_name='Размер, байт')),
                ('row_count', models.IntegerField(default=0, verbose_name='Число строк')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задание на выгрузку',
                'verbose_name_plural': 'Центр выгрузок',
                'db_table': 'app_export_job',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IncidentSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_severity', models.SmallIntegerField(default=3, verbose_name='Минимальная серьёзность')),
                ('cargo_only', models.BooleanField(default=True, verbose_name='Только влияющие на грузовой транспорт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.district', verbose_name='Округ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на инциденты',
                'verbose_name_plural': 'Подписки на инциденты',
                'db_table': 'app_incident_subscription',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('alert', 'Тревога')], default='info', max_length=16, verbose_name='Уровень')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('body', models.CharField(blank=True, default='', max_length=1000, verbose_name='Текст')),
                ('url', models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'app_notification',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('page', models.CharField(max_length=64, verbose_name='Страница')),
                ('query', models.CharField(blank=True, default='', max_length=1000, verbose_name='Условия отбора')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Пояснение')),
                ('share_token', models.CharField(blank=True, default='', max_length=32, verbose_name='Токен доступа')),
                ('is_public', models.BooleanField(default=False, verbose_name='Доступен по ссылке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('last_opened', models.DateTimeField(blank=True, null=True, verbose_name='Последнее открытие')),
                ('open_count', models.IntegerField(default=0, verbose_name='Число открытий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сохранённый вид',
                'verbose_name_plural': 'Сохранённые виды',
                'db_table': 'app_saved_view',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Наблюдатель'), ('analyst', 'Аналитик'), ('operator', 'Диспетчер'), ('admin', 'Администратор')], db_index=True, default='viewer', max_length=16, verbose_name='Роль')),
                ('organization', models.CharField(blank=True, default='', max_length=200, verbose_name='Организация')),
                ('position', models.CharField(blank=True, default='', max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон')),
                ('theme', models.CharField(choices=[('auto', 'Как в системе'), ('dark', 'Тёмное'), ('light', 'Светлое')], default='auto', max_length=8, verbose_name='Оформление')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=8, verbose_name='Язык интерфейса')),
                ('notify_incidents', models.BooleanField(default=True, verbose_name='Уведомлять об инцидентах')),
                ('api_token', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Токен REST API')),
                ('api_token_created', models.DateTimeField(blank=True, null=True, verbose_name='Токен выпущен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('default_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.district', verbose_name='Округ по умолчанию')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'app_user_profile',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('object', 'Объект инфраструктуры'), ('district', 'Округ'), ('road', 'Участок дороги'), ('route', 'Грузовой маршрут')], max_length=16, verbose_name='Тип')),
                ('target_id', models.IntegerField(verbose_name='Идентификатор объекта')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Наименование')),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Избранное',
                'db_table': 'app_favorite',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'target_id'), name='uniq_favorite_per_user')],
            },
        ),
    ]
