# Generated by Django 6.0.7 on 2026-09-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='api_token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_token_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Отпечаток токена'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_token_prefix',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Начало токена'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_token_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обращение'),
        ),
    ]
