# Generated by Django 6.0.7 on 2026-09-04 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_api_token_digest'),
        ('core', '0012_object_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_district',
            field=models.ForeignKey(blank=True, help_text='Округ, которым разделы системы ограничиваются при первом открытии. Заданный в самом разделе отбор рабочую область замещает', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.district', verbose_name='Рабочая область'),
        ),
    ]
