# Generated by Django 6.0.7 on 2026-09-04 22:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_working_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=64, verbose_name='Раздел')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование раздела')),
                ('query', models.CharField(blank=True, default='', max_length=500, verbose_name='Условия отбора')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее обращение')),
                ('open_count', models.IntegerField(default=1, verbose_name='Число обращений')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение к данным',
                'verbose_name_plural': 'История запросов',
                'db_table': 'app_query_history',
                'ordering': ('-opened_at',),
                'indexes': [models.Index(fields=['user', '-opened_at'], name='idx_history_recent')],
                'constraints': [models.UniqueConstraint(fields=('user', 'route', 'query'), name='uniq_history_per_query')],
            },
        ),
    ]
