# Generated by Django 6.0.7 on 2026-07-26 04:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=48, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, default='', max_length=400, verbose_name='Описание')),
                ('order', models.SmallIntegerField(default=100, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Рубрика материалов',
                'verbose_name_plural': 'Рубрики материалов',
                'db_table': 'app_article_category',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=48, unique=True, verbose_name='Код страницы')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('lead', models.CharField(blank=True, default='', max_length=600, verbose_name='Вводный текст')),
                ('body', models.TextField(verbose_name='Содержание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Информационная страница',
                'verbose_name_plural': 'Информационные страницы',
                'db_table': 'app_static_page',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Представление')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('organization', models.CharField(blank=True, default='', max_length=200, verbose_name='Организация')),
                ('topic', models.CharField(choices=[('data', 'Замечание к данным'), ('feature', 'Предложение по развитию'), ('error', 'Сообщение об ошибке'), ('access', 'Вопрос по доступу'), ('other', 'Иное')], max_length=16, verbose_name='Тема обращения')),
                ('message', models.TextField(verbose_name='Текст обращения')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback/%Y/%m/', verbose_name='Вложение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_work', 'В работе'), ('answered', 'Отвечено'), ('closed', 'Закрыто')], db_index=True, default='new', max_length=16, verbose_name='Состояние')),
                ('answer', models.TextField(blank=True, default='', verbose_name='Ответ')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, default='', max_length=300, verbose_name='Клиент')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Поступило')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обратная связь',
                'db_table': 'app_feedback_message',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Адресный код')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('lead', models.CharField(blank=True, default='', max_length=600, verbose_name='Краткое содержание')),
                ('body', models.TextField(verbose_name='Текст материала')),
                ('reading_minutes', models.SmallIntegerField(default=5, verbose_name='Время чтения, мин')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('is_featured', models.BooleanField(default=False, verbose_name='На главной')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('view_count', models.IntegerField(default=0, verbose_name='Число просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='content.articlecategory', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Аналитический материал',
                'verbose_name_plural': 'Аналитические материалы',
                'db_table': 'app_article',
                'ordering': ('-published_at',),
                'indexes': [models.Index(fields=['-published_at'], name='idx_article_published')],
            },
        ),
    ]
