# Generated by Django 6.0.7 on 2026-07-26 04:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import geo.fields
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Расширения PostgreSQL. На SQLite операция является пустой: класс
        # CreateExtension самостоятельно проверяет тип СУБД и ничего не делает
        # для остальных бэкендов. Это позволяет держать один набор миграций
        # для обоих поддерживаемых контуров.
        CreateExtension("postgis"),
        CreateExtension("pg_trgm"),
        migrations.CreateModel(
            name='CargoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('hazard_class', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Класс опасности ADR')),
            ],
            options={
                'verbose_name': 'Категория груза',
                'verbose_name_plural': 'Категории грузов',
                'db_table': 'cargo_categories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('source_type', models.CharField(choices=[('api', 'Программный интерфейс (API)'), ('csv', 'Выгрузка CSV'), ('open_data', 'Портал открытых данных'), ('gis_service', 'Геоинформационный сервис'), ('manual', 'Ручной ввод')], max_length=32, verbose_name='Тип источника')),
                ('url', models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес')),
                ('update_frequency', models.CharField(blank=True, choices=[('hourly', 'Ежечасно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально')], default='', max_length=32, verbose_name='Периодичность обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник данных',
                'verbose_name_plural': 'Источники данных',
                'db_table': 'data_sources',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Наименование')),
                ('short_name', models.CharField(max_length=16, unique=True, verbose_name='Аббревиатура')),
                ('area_sq_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь, км²')),
                ('population', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Численность населения, чел.')),
                ('geom', geo.fields.MultiPolygonField(blank=True, null=True, verbose_name='Границы округа')),
                ('center', geo.fields.PointField(blank=True, null=True, verbose_name='Центр округа')),
            ],
            options={
                'verbose_name': 'Административный округ',
                'verbose_name_plural': 'Административные округа',
                'db_table': 'districts',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InfrastructureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип объекта инфраструктуры',
                'verbose_name_plural': 'Типы объектов инфраструктуры',
                'db_table': 'infrastructure_types',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CargoRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('route_type', models.CharField(choices=[('inbound', 'Ввоз в город'), ('outbound', 'Вывоз из города'), ('transit', 'Транзит')], max_length=16, verbose_name='Тип маршрута')),
                ('origin_region', models.CharField(blank=True, default='', max_length=120, verbose_name='Регион отправления')),
                ('destination', models.CharField(blank=True, default='', max_length=120, verbose_name='Регион назначения')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Протяжённость, км')),
                ('avg_duration_h', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Среднее время в пути, ч')),
                ('truck_count_day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Интенсивность, ТС/сут.')),
                ('geom', geo.fields.LineStringField(blank=True, null=True, verbose_name='Геометрия маршрута')),
                ('source', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='core.datasource', verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'Грузовой маршрут',
                'verbose_name_plural': 'Грузовые маршруты',
                'db_table': 'cargo_routes',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EtlRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('target_table', models.CharField(max_length=64, verbose_name='Целевая таблица')),
                ('records_loaded', models.IntegerField(default=0, verbose_name='Загружено записей')),
                ('records_errors', models.IntegerField(default=0, verbose_name='Отклонено записей')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('partial', 'С замечаниями'), ('failed', 'Ошибка')], default='running', max_length=16, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке')),
                ('source', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_runs', to='core.datasource', verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'Загрузка данных',
                'verbose_name_plural': 'Журнал загрузок данных',
                'db_table': 'etl_log',
                'ordering': ('-started_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('road_class', models.CharField(choices=[('highway', 'Магистраль скоростного движения'), ('arterial', 'Магистраль общегородского значения'), ('collector', 'Улица районного значения')], max_length=32, verbose_name='Класс дороги')),
                ('lanes', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)], verbose_name='Число полос')),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Протяжённость, км')),
                ('speed_limit_kmh', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(130)], verbose_name='Разрешённая скорость, км/ч')),
                ('geom', geo.fields.LineStringField(blank=True, null=True, verbose_name='Геометрия участка')),
                ('district', models.ForeignKey(blank=True, db_column='district_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roads', to='core.district', verbose_name='Округ')),
                ('source', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roads', to='core.datasource', verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'Участок дорожной сети',
                'verbose_name_plural': 'Участки дорожной сети',
                'db_table': 'road_segments',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FreightFlowStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(verbose_name='Начало периода')),
                ('period_type', models.CharField(choices=[('day', 'Сутки'), ('week', 'Неделя'), ('month', 'Месяц'), ('quarter', 'Квартал'), ('year', 'Год')], default='month', max_length=16, verbose_name='Тип периода')),
                ('direction', models.CharField(choices=[('in', 'Ввоз'), ('out', 'Вывоз'), ('transit', 'Транзит')], max_length=16, verbose_name='Направление')),
                ('volume_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Объём, т')),
                ('vehicle_count', models.IntegerField(blank=True, null=True, verbose_name='Число рейсов')),
                ('avg_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Средняя скорость, км/ч')),
                ('cargo_category', models.ForeignKey(blank=True, db_column='cargo_cat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_stats', to='core.cargocategory', verbose_name='Категория груза')),
                ('district', models.ForeignKey(blank=True, db_column='district_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_stats', to='core.district', verbose_name='Округ')),
                ('route', models.ForeignKey(blank=True, db_column='route_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_stats', to='core.cargoroute', verbose_name='Маршрут')),
                ('source', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_stats', to='core.datasource', verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'Показатель грузопотока',
                'verbose_name_plural': 'Статистика грузопотоков',
                'db_table': 'freight_flow_stats',
                'ordering': ('-period_date', 'id'),
                'indexes': [models.Index(fields=['period_date'], name='idx_flow_period'), models.Index(fields=['district', 'period_date'], name='idx_flow_district')],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес')),
                ('capacity_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Мощность хранения, т')),
                ('area_sq_m', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь, м²')),
                ('operating_hours', models.CharField(blank=True, default='', max_length=64, verbose_name='Режим работы')),
                ('geom', geo.fields.PointField(blank=True, null=True, verbose_name='Координаты')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('district', models.ForeignKey(db_column='district_id', on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='core.district', verbose_name='Округ')),
                ('source', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='core.datasource', verbose_name='Источник данных')),
                ('type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='core.infrastructuretype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Объект инфраструктуры',
                'verbose_name_plural': 'Объекты инфраструктуры',
                'db_table': 'infrastructure_objects',
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['district'], name='idx_infra_district'), models.Index(fields=['type'], name='idx_infra_type')],
            },
        ),
        migrations.CreateModel(
            name='TrafficCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(verbose_name='Время замера')),
                ('congestion_level', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Балл загруженности')),
                ('avg_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Средняя скорость, км/ч')),
                ('travel_time_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Время проезда, мин')),
                ('vehicle_density', models.IntegerField(blank=True, null=True, verbose_name='Плотность потока, ТС/км')),
                ('incident_flag', models.BooleanField(default=False, verbose_name='Есть инцидент')),
                ('road', models.ForeignKey(db_column='road_id', on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.roadsegment', verbose_name='Участок')),
                ('source', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_records', to='core.datasource', verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'Замер дорожной обстановки',
                'verbose_name_plural': 'Дорожная обстановка',
                'db_table': 'traffic_conditions',
                'ordering': ('-recorded_at', 'id'),
                'indexes': [models.Index(fields=['road', '-recorded_at'], name='idx_traffic_road_time'), models.Index(fields=['-recorded_at'], name='idx_traffic_time')],
            },
        ),
        migrations.CreateModel(
            name='TrafficIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(verbose_name='Зарегистрирован')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Устранён')),
                ('incident_type', models.CharField(choices=[('accident', 'Дорожно-транспортное происшествие'), ('roadworks', 'Дорожные работы'), ('restriction', 'Ограничение движения'), ('weather', 'Погодные условия'), ('event', 'Массовое мероприятие'), ('other', 'Прочее')], max_length=32, verbose_name='Тип события')),
                ('severity', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Серьёзность')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('geom', geo.fields.PointField(blank=True, null=True, verbose_name='Координаты')),
                ('affects_cargo', models.BooleanField(default=False, verbose_name='Влияет на грузовой транспорт')),
                ('road', models.ForeignKey(blank=True, db_column='road_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.roadsegment', verbose_name='Участок')),
                ('source', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.datasource', verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'Дорожный инцидент',
                'verbose_name_plural': 'Дорожные инциденты',
                'db_table': 'traffic_incidents',
                'ordering': ('-reported_at', 'id'),
                'indexes': [models.Index(fields=['-reported_at'], name='idx_incidents_time')],
            },
        ),
    ]
