# Generated by Django 6.0.7 on 2026-09-03 21:52

import geo.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructureobject',
            name='area_origin',
            field=models.CharField(blank=True, choices=[('measured', 'Измерено'), ('derived', 'Рассчитано'), ('modelled', 'Смоделировано')], default='', help_text='Откуда получено значение площади', max_length=16, verbose_name='Происхождение площади'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='capacity_origin',
            field=models.CharField(blank=True, choices=[('measured', 'Измерено'), ('derived', 'Рассчитано'), ('modelled', 'Смоделировано')], default='', help_text='Откуда получено значение мощности хранения', max_length=16, verbose_name='Происхождение мощности'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='classification_rule',
            field=models.CharField(blank=True, default='', help_text='Обозначение правила, по которому объект отнесён к типу', max_length=32, verbose_name='Правило отнесения'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='footprint',
            field=geo.fields.MultiPolygonField(blank=True, null=True, verbose_name='Контур объекта'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='operator',
            field=models.CharField(blank=True, default='', help_text='Организация, эксплуатирующая объект', max_length=200, verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='osm_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор OSM'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='osm_type',
            field=models.CharField(blank=True, choices=[('node', 'Точка'), ('way', 'Линия'), ('relation', 'Отношение')], default='', max_length=10, verbose_name='Тип элемента OSM'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, help_text='Момент выгрузки, из которой получена запись', null=True, verbose_name='Данные источника от'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='website',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Сайт'),
        ),
        migrations.AddIndex(
            model_name='infrastructureobject',
            index=models.Index(fields=['osm_type', 'osm_id'], name='idx_infra_osm'),
        ),
        migrations.AddConstraint(
            model_name='infrastructureobject',
            constraint=models.UniqueConstraint(condition=models.Q(('osm_id__isnull', False)), fields=('osm_type', 'osm_id'), name='uniq_infra_osm_element'),
        ),
    ]
