# Generated by Django 6.0.7 on 2026-09-03 23:13

import geo.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_real_data_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsegment',
            name='allows_hgv',
            field=models.BooleanField(blank=True, help_text='Пустое значение означает, что ограничение не размечено', null=True, verbose_name='Открыта для грузового движения'),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='length_origin',
            field=models.CharField(blank=True, choices=[('measured', 'Измерено'), ('derived', 'Рассчитано'), ('modelled', 'Смоделировано')], default='', max_length=16, verbose_name='Происхождение протяжённости'),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='ref',
            field=models.CharField(blank=True, default='', help_text='Номер федеральной или региональной трассы: М-4, А-103', max_length=32, verbose_name='Учётный номер'),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='segment_count',
            field=models.IntegerField(default=0, help_text='Число участков, из которых собрана магистраль', verbose_name='Частей в исходных данных'),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Данные источника от'),
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='geom',
            field=geo.fields.MultiLineStringField(blank=True, null=True, verbose_name='Геометрия магистрали'),
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='road_class',
            field=models.CharField(choices=[('highway', 'Магистраль скоростного движения'), ('arterial', 'Магистраль общегородского значения, непрерывное движение'), ('collector', 'Магистраль общегородского значения, регулируемое движение')], max_length=32, verbose_name='Класс дороги'),
        ),
    ]
