# Generated by Django 6.0.7 on 2026-09-03 23:48

import django.db.models.deletion
import geo.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_road_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictionZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('short_name', models.CharField(max_length=32, verbose_name='Краткое наименование')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('level', models.SmallIntegerField(help_text='1 — внешняя зона; пропуск во внутреннюю действует во внешних', verbose_name='Уровень вложенности')),
                ('permit_required_from_tons', models.DecimalField(decimal_places=2, help_text='Разрешённая максимальная масса, начиная с которой нужен пропуск', max_digits=6, verbose_name='Пропуск требуется при РММ от, т')),
                ('min_ecological_class', models.SmallIntegerField(blank=True, help_text='Класс «Евро», ниже которого въезд запрещён', null=True, verbose_name='Наименьший экологический класс')),
                ('seasonal_limit_tons', models.DecimalField(blank=True, decimal_places=2, help_text='Действует с 1 мая по 1 октября в выходные и праздничные дни', max_digits=6, null=True, verbose_name='Сезонное ограничение при РММ от, т')),
                ('fine_rubles', models.IntegerField(blank=True, null=True, verbose_name='Штраф за нарушение, ₽')),
                ('legal_basis', models.CharField(blank=True, default='', max_length=200, verbose_name='Нормативное основание')),
                ('geom', geo.fields.MultiPolygonField(blank=True, null=True, verbose_name='Граница зоны')),
                ('area_sq_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь, км²')),
                ('perimeter_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Периметр, км')),
                ('geometry_origin', models.CharField(blank=True, choices=[('measured', 'Измерено'), ('derived', 'Рассчитано'), ('modelled', 'Смоделировано')], default='', max_length=16, verbose_name='Происхождение границы')),
                ('source_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Данные источника от')),
                ('boundary_road', models.ForeignKey(blank=True, db_column='boundary_road_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounded_zones', to='core.roadsegment', verbose_name='Магистраль-граница')),
            ],
            options={
                'verbose_name': 'Зона ограничения движения',
                'verbose_name_plural': 'Зоны ограничения движения',
                'db_table': 'restriction_zones',
                'ordering': ('level',),
            },
        ),
    ]
