# Generated by Django 6.0.7 on 2026-09-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_restriction_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsegment',
            name='freight_frame_kind',
            field=models.CharField(blank=True, default='', help_text='Кольцевая, вылетная, хордовая магистраль', max_length=16, verbose_name='Роль в каркасе'),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='in_freight_frame',
            field=models.BooleanField(blank=True, help_text='По перечню Департамента транспорта. Вне каркаса движение транспорта тяжелее 2,5 т допускается только для доставки груза до адреса внутри района. Пустое значение — сведений нет', null=True, verbose_name='Входит в грузовой каркас'),
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='allows_hgv',
            field=models.BooleanField(blank=True, help_text='По разметке OpenStreetMap; пустое значение — сведений нет', null=True, verbose_name='Разметка допускает грузовое движение'),
        ),
    ]
