# Generated by Django 6.0.7 on 2026-09-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_freight_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightflowstat',
            name='origin',
            field=models.CharField(blank=True, choices=[('measured', 'Измерено'), ('derived', 'Рассчитано'), ('modelled', 'Смоделировано')], default='', max_length=16, verbose_name='Происхождение показателя'),
        ),
        migrations.AddField(
            model_name='trafficcondition',
            name='model_explanation',
            field=models.CharField(blank=True, default='', help_text='Вклад составляющих модели в итоговый балл', max_length=300, verbose_name='Разложение оценки'),
        ),
        migrations.AddField(
            model_name='trafficcondition',
            name='origin',
            field=models.CharField(blank=True, choices=[('measured', 'Измерено'), ('derived', 'Рассчитано'), ('modelled', 'Смоделировано')], default='', help_text='Данных о загруженности в открытом доступе нет; значение рассчитывается имитационной моделью', max_length=16, verbose_name='Происхождение оценки'),
        ),
    ]
