# Generated by Django 6.0.7 on 2026-09-04 00:46

import geo.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_simulation_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoroute',
            name='geom',
            field=geo.fields.MultiLineStringField(blank=True, null=True, verbose_name='Геометрия коридора'),
        ),
    ]
