# Generated by Django 6.0.7 on 2026-09-04 01:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_corridor_geometry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlReject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='', help_text='Элемент выгрузки или номер строки файла', max_length=120, verbose_name='Положение в источнике')),
                ('record_key', models.CharField(blank=True, default='', max_length=200, verbose_name='Ключ записи')),
                ('check_code', models.CharField(max_length=64, verbose_name='Код проверки')),
                ('message', models.CharField(max_length=500, verbose_name='Причина отклонения')),
                ('payload', models.TextField(blank=True, default='', help_text='Содержимое записи в том виде, в каком оно поступило', verbose_name='Исходная запись')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Отложено')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Разобрано')),
            ],
            options={
                'verbose_name': 'Запись в карантине',
                'verbose_name_plural': 'Карантин загрузки',
                'db_table': 'etl_rejects',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='etlrun',
            name='actor',
            field=models.ForeignKey(blank=True, db_column='actor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_runs', to=settings.AUTH_USER_MODEL, verbose_name='Начал загрузку'),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='parameters',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Параметры запуска'),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='pipeline',
            field=models.CharField(blank=True, default='', help_text='Обозначение процедуры загрузки в реестре конвейеров', max_length=64, verbose_name='Конвейер'),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='records_created',
            field=models.IntegerField(default=0, verbose_name='Создано записей'),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='records_removed',
            field=models.IntegerField(default=0, verbose_name='Удалено записей'),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='records_unchanged',
            field=models.IntegerField(default=0, verbose_name='Без изменений'),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='records_updated',
            field=models.IntegerField(default=0, verbose_name='Обновлено записей'),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='trigger',
            field=models.CharField(choices=[('schedule', 'По расписанию'), ('console', 'Из панели администратора'), ('upload', 'Загрузка файла пользователем'), ('cli', 'Из командной строки')], default='cli', max_length=16, verbose_name='Начало загрузки'),
        ),
        migrations.AddField(
            model_name='freightflowstat',
            name='external_key',
            field=models.CharField(blank=True, default='', help_text='Обозначение, по которому запись сопоставляется с исходной при повторной загрузке. Обеспечивает обновление вместо дублирования', max_length=120, verbose_name='Ключ записи в источнике'),
        ),
        migrations.AddField(
            model_name='freightflowstat',
            name='scope',
            field=models.CharField(choices=[('all', 'Все перевозчики'), ('commercial', 'На коммерческой основе')], default='all', max_length=16, verbose_name='Круг перевозчиков'),
        ),
        migrations.AddField(
            model_name='freightflowstat',
            name='territory',
            field=models.CharField(blank=True, default='', help_text='Наименование территории в ведомственной статистике: субъект федерации или федеральный округ. Для внутригородских рядов не заполняется — территорию задаёт округ', max_length=120, verbose_name='Территория'),
        ),
        migrations.AddField(
            model_name='freightflowstat',
            name='turnover_ton_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Произведение массы груза на расстояние перевозки. Показатель самостоятельный: рост перевозок при падении грузооборота означает укорочение плеча доставки', max_digits=18, null=True, verbose_name='Грузооборот, т·км'),
        ),
        migrations.AddField(
            model_name='trafficincident',
            name='external_key',
            field=models.CharField(blank=True, default='', help_text='Обозначение исходной записи. По нему событие обновляется при повторной загрузке вместо появления второй записи о том же', max_length=120, verbose_name='Ключ записи в источнике'),
        ),
        migrations.AddField(
            model_name='trafficincident',
            name='origin',
            field=models.CharField(blank=True, choices=[('measured', 'Измерено'), ('derived', 'Рассчитано'), ('modelled', 'Смоделировано')], default='', max_length=16, verbose_name='Происхождение сведений'),
        ),
        migrations.AlterField(
            model_name='freightflowstat',
            name='direction',
            field=models.CharField(choices=[('in', 'Ввоз'), ('out', 'Вывоз'), ('transit', 'Транзит'), ('total', 'Всего')], max_length=16, verbose_name='Направление'),
        ),
        migrations.AddConstraint(
            model_name='freightflowstat',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key', ''), _negated=True), fields=('source', 'external_key'), name='uq_flow_external_key'),
        ),
        migrations.AddConstraint(
            model_name='trafficincident',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key', ''), _negated=True), fields=('source', 'external_key'), name='uq_incident_external_key'),
        ),
        migrations.AddField(
            model_name='etlreject',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_rejects_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Разобрал'),
        ),
        migrations.AddField(
            model_name='etlreject',
            name='run',
            field=models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, related_name='rejects', to='core.etlrun', verbose_name='Загрузка'),
        ),
        migrations.AddIndex(
            model_name='etlreject',
            index=models.Index(fields=['-created_at'], name='idx_rejects_time'),
        ),
        migrations.AddIndex(
            model_name='etlreject',
            index=models.Index(fields=['check_code'], name='idx_rejects_check'),
        ),
    ]
