# Generated by Django 6.0.7 on 2026-09-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_etl_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('api', 'Программный интерфейс (API)'), ('csv', 'Выгрузка CSV'), ('open_data', 'Портал открытых данных'), ('gis_service', 'Геоинформационный сервис'), ('manual', 'Ручной ввод'), ('model', 'Расчётная модель')], max_length=32, verbose_name='Тип источника'),
        ),
    ]
