# Generated by Django 6.0.7 on 2026-09-04 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_model_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficincident',
            name='district',
            field=models.ForeignKey(blank=True, db_column='district_id', help_text='Округ, в границы которого попадает координата события. Определяется по координате, а не по участку: событие размечается и там, где магистрали в реестре нет', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.district', verbose_name='Округ'),
        ),
    ]
