# Generated by Django 6.0.7 on 2026-09-04 19:17

import django.db.models.deletion
import geo.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_incident_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('water', 'Водная поверхность'), ('green', 'Зелёный массив')], max_length=16, verbose_name='Вид территории')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Наименование')),
                ('geom', geo.fields.MultiPolygonField(blank=True, null=True, verbose_name='Контур')),
                ('area_sq_m', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Площадь, м²')),
                ('osm_type', models.CharField(blank=True, choices=[('node', 'Точка'), ('way', 'Линия'), ('relation', 'Отношение')], default='', max_length=10, verbose_name='Тип элемента OSM')),
                ('osm_id', models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор OSM')),
                ('source_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Данные источника от')),
                ('source', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='natural_areas', to='core.datasource', verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'Природная территория',
                'verbose_name_plural': 'Природные территории',
                'db_table': 'natural_areas',
                'ordering': ('-area_sq_m', 'id'),
                'indexes': [models.Index(fields=['kind'], name='natural_areas_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('osm_type', 'osm_id'), name='natural_areas_osm_element_unique')],
            },
        ),
    ]
