# Generated by Django 6.0.7 on 2026-09-04 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_naturalarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructureobject',
            name='verification',
            field=models.CharField(blank=True, choices=[('', 'Не проверялась'), ('confirmed', 'Подтверждена'), ('disputed', 'Требует уточнения')], default='', max_length=16, verbose_name='Осмотр'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='verification_note',
            field=models.CharField(blank=True, default='', help_text='Что именно расходится с действительностью', max_length=300, verbose_name='Замечание осмотра'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Осмотрена'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_column='verified_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_objects', to=settings.AUTH_USER_MODEL, verbose_name='Осмотр выполнил'),
        ),
        migrations.AddIndex(
            model_name='infrastructureobject',
            index=models.Index(fields=['verification'], name='idx_infra_verification'),
        ),
    ]
